version: "3.7"

volumes:
  mysql-elmonitor:
    driver: local
    driver_opts:
      type: none
      device: /home/raul/docker-data/mysql-elmonitor
      o: bind
  web-elmonitor:
    driver: local
    driver_opts:
      type: none
      device: /home/raul/elmonitor-projects/web
      o: bind

networks:
  elmonitor-net:
    driver: bridge

services:
  mysql-elmonitor:
    image: mysql/mysql-server:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-elmonitor:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - elmonitor-net
  web-elmonitor:
    build:
      context: /home/raul/elmonitor-projects/docker/elmonitor/web/5.6
    volumes:
      - web-elmonitor:/var/www/app/
    networks:
      - elmonitor-net

